version: "3.8"

services:
  admin:
    build:
      context: ./frontend/admin
    container_name: admin
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - app-network

  customer-service-demo:
    build:
      context: ./frontend/customer-service-demo
    container_name: customer-service-demo
    ports:
      - "3001:80"
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    extra_hosts:               # <-- magic line
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge